### ISSUE TITLE
咨询code问题

### ISSUE THREAD

**Issue by xiaoxusanheyi** [SirJamie/sgm3d#7]
1.双目的模型是PSMNet，那么单目的模型你们用的是哪个？ CaDDN吗？
 2.github公开的代码中，是否可以给指出创新的MG-DA和IOU-MA的代码开始位置呢？给出跳转链接即可
 3.补充了一个实验code问题：我在训练的时候，一直出现这个问题：RuntineError: Tined out initializing process group in store based barrier on rank: 1, for key:store_based_barrier_key:1 (world_size=1, worker_count=2,timeout=2:00:00)
是怎么回事？网上的一些超时修改方法也都尝试了，但还是存在这个问题。你们在训练的过程中遇到过吗？我该怎么解决该问题呢？

**Comment by zhouzheyuan** [comment]
1. We use CaDDN as our monocular model.
2. Please refer to https://github.com/zhouzheyuan/sgm3d/blob/397bff28e4a331f6fe96dd02b2bfd259d94dcb13/pcdet/models/dense_heads/anchor_head_single_sgm.py#L28
3. Sorry we didn't encountering this problem. It seems to be caused by an improper configuration of the environment. You could refer to the original OpenPCDet repository to see if there is a corresponding solution.

**Comment by xiaoxusanheyi** [comment]
感谢你的回复！
